"""initial

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-09

Real autogenerated baseline schema, replacing the old no-op stamp migration
(see git history) that relied on Base.metadata.create_all() at startup —
create_all() can create missing tables but can never ALTER an existing
populated one (e.g. it silently skipped adding shift_schedules.
last_generated_date to any database that already existed before that column
was added). From here on, schema changes should ship as new alembic
revisions (`alembic revision --autogenerate -m "..."`), and `alembic upgrade
head` is what actually evolves a database — create_all() in app/core/db.py
is kept only as a harmless idempotent safety net for local dev.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('urgency_threshold', sa.String(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'module', name='uq_alert_settings_tenant_module')
    )
    op.create_index(op.f('ix_alert_settings_tenant_id'), 'alert_settings', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversations_tenant_id'), 'chat_conversations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_user_id'), 'chat_conversations', ['user_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('reorder_point', sa.Float(), nullable=False),
    sa.Column('supplier_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('bill_of_materials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sku', name='uq_inventory_items_tenant_sku')
    )
    op.create_index(op.f('ix_inventory_items_tenant_id'), 'inventory_items', ['tenant_id'], unique=False)
    op.create_table('lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('line_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('products', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_rate_per_hour', sa.Float(), nullable=False),
    sa.Column('shift_target_units', sa.Integer(), nullable=False),
    sa.Column('ideal_cycle_time_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'line_code', name='uq_lines_tenant_line_code')
    )
    op.create_index(op.f('ix_lines_tenant_id'), 'lines', ['tenant_id'], unique=False)
    op.create_table('module_freshness',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expected_cadence_hours', sa.Integer(), nullable=False),
    sa.Column('last_nudged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_freshness_tenant_id'), 'module_freshness', ['tenant_id'], unique=False)
    op.create_table('onboarding_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('step_key', sa.String(length=100), nullable=False),
    sa.Column('completed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_progress_tenant_id'), 'onboarding_progress', ['tenant_id'], unique=False)
    op.create_table('pm_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('asset_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('line_area', sa.String(length=100), nullable=False),
    sa.Column('criticality', sa.String(length=10), nullable=False),
    sa.Column('monitored_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('service_intervals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'asset_code', name='uq_pm_asset_tenant_code')
    )
    op.create_index(op.f('ix_pm_assets_tenant_id'), 'pm_assets', ['tenant_id'], unique=False)
    op.create_table('quality_characteristics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.String(length=100), nullable=False),
    sa.Column('characteristic_name', sa.String(length=255), nullable=False),
    sa.Column('nominal_value', sa.Float(), nullable=False),
    sa.Column('tolerance', sa.Float(), nullable=False),
    sa.Column('inspection_type', sa.String(length=100), nullable=False),
    sa.Column('line_id', sa.String(length=100), nullable=False),
    sa.Column('station_id', sa.String(length=100), nullable=False),
    sa.Column('defect_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quality_char_tenant_part_name', 'quality_characteristics', ['tenant_id', 'part_id', 'characteristic_name'], unique=False)
    op.create_index(op.f('ix_quality_characteristics_tenant_id'), 'quality_characteristics', ['tenant_id'], unique=False)
    op.create_table('quality_inspection_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('characteristic_name', sa.String(length=255), nullable=False),
    sa.Column('measured_value', sa.Float(), nullable=False),
    sa.Column('pass_fail', sa.Boolean(), nullable=False),
    sa.Column('defect_type', sa.String(length=255), nullable=True),
    sa.Column('line_id', sa.String(length=100), nullable=False),
    sa.Column('station_id', sa.String(length=100), nullable=False),
    sa.Column('inspector', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quality_insp_tenant_line_ts', 'quality_inspection_records', ['tenant_id', 'line_id', 'timestamp'], unique=False)
    op.create_index('ix_quality_insp_tenant_part_char_ts', 'quality_inspection_records', ['tenant_id', 'part_id', 'characteristic_name', 'timestamp'], unique=False)
    op.create_index(op.f('ix_quality_inspection_records_tenant_id'), 'quality_inspection_records', ['tenant_id'], unique=False)
    op.create_table('sent_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('issue', sa.String(length=255), nullable=False),
    sa.Column('last_urgency', sa.String(length=10), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'asset_name', 'issue', name='uq_sent_alerts_tenant_asset_issue')
    )
    op.create_index(op.f('ix_sent_alerts_tenant_id'), 'sent_alerts', ['tenant_id'], unique=False)
    op.create_table('shift_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('areas', sa.JSON(), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('last_generated_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_schedules_tenant_id'), 'shift_schedules', ['tenant_id'], unique=False)
    op.create_table('sop_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sop_documents_tenant_id'), 'sop_documents', ['tenant_id'], unique=False)
    op.create_table('sop_query_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('matched_document_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sop_query_logs_tenant_id'), 'sop_query_logs', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_tenant_id'), 'chat_messages', ['tenant_id'], unique=False)
    op.create_table('inventory_stock_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('current_qty', sa.Float(), nullable=False),
    sa.Column('qty_in', sa.Float(), nullable=False),
    sa.Column('qty_out', sa.Float(), nullable=False),
    sa.Column('movement_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_stock_movements_item_id'), 'inventory_stock_movements', ['item_id'], unique=False)
    op.create_index('ix_inventory_stock_movements_item_ts', 'inventory_stock_movements', ['item_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_inventory_stock_movements_tenant_id'), 'inventory_stock_movements', ['tenant_id'], unique=False)
    op.create_table('output_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('units_produced', sa.Integer(), nullable=False),
    sa.Column('units_good', sa.Integer(), nullable=False),
    sa.Column('units_reject', sa.Integer(), nullable=False),
    sa.Column('run_state', sa.String(length=10), nullable=False),
    sa.Column('downtime_minutes', sa.Float(), nullable=False),
    sa.Column('downtime_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_output_logs_line_id'), 'output_logs', ['line_id'], unique=False)
    op.create_index('ix_output_logs_line_timestamp', 'output_logs', ['line_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_output_logs_tenant_id'), 'output_logs', ['tenant_id'], unique=False)
    op.create_table('pm_maintenance_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('downtime_hours', sa.Float(), nullable=False),
    sa.Column('parts_replaced', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['pm_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pm_maintenance_history_asset_id'), 'pm_maintenance_history', ['asset_id'], unique=False)
    op.create_index(op.f('ix_pm_maintenance_history_tenant_id'), 'pm_maintenance_history', ['tenant_id'], unique=False)
    op.create_table('pm_sensor_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['pm_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pm_readings_asset_metric_ts', 'pm_sensor_readings', ['asset_id', 'metric', 'timestamp'], unique=False)
    op.create_index(op.f('ix_pm_sensor_readings_asset_id'), 'pm_sensor_readings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_pm_sensor_readings_tenant_id'), 'pm_sensor_readings', ['tenant_id'], unique=False)
    op.create_table('quality_holds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.String(length=100), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('released_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['released_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_holds_tenant_id'), 'quality_holds', ['tenant_id'], unique=False)
    op.create_index('ix_quality_holds_tenant_status', 'quality_holds', ['tenant_id', 'status'], unique=False)
    op.create_table('shift_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('shift_schedule_id', sa.Integer(), nullable=True),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('compiled_content', sa.JSON(), nullable=False),
    sa.Column('next_shift_actions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shift_schedule_id'], ['shift_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_reports_tenant_id'), 'shift_reports', ['tenant_id'], unique=False)
    op.create_table('sop_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['sop_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sop_chunks_document_id'), 'sop_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_sop_chunks_tenant_id'), 'sop_chunks', ['tenant_id'], unique=False)
    op.create_table('pm_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('issue_key', sa.String(length=100), nullable=False),
    sa.Column('issue', sa.String(length=255), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(length=10), nullable=False),
    sa.Column('estimated_window', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_alerted_urgency', sa.String(length=10), nullable=True),
    sa.Column('linked_maintenance_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['pm_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_maintenance_id'], ['pm_maintenance_history.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pm_recommendations_asset_id'), 'pm_recommendations', ['asset_id'], unique=False)
    op.create_index(op.f('ix_pm_recommendations_tenant_id'), 'pm_recommendations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pm_recommendations_tenant_id'), table_name='pm_recommendations')
    op.drop_index(op.f('ix_pm_recommendations_asset_id'), table_name='pm_recommendations')
    op.drop_table('pm_recommendations')
    op.drop_index(op.f('ix_sop_chunks_tenant_id'), table_name='sop_chunks')
    op.drop_index(op.f('ix_sop_chunks_document_id'), table_name='sop_chunks')
    op.drop_table('sop_chunks')
    op.drop_index(op.f('ix_shift_reports_tenant_id'), table_name='shift_reports')
    op.drop_table('shift_reports')
    op.drop_index('ix_quality_holds_tenant_status', table_name='quality_holds')
    op.drop_index(op.f('ix_quality_holds_tenant_id'), table_name='quality_holds')
    op.drop_table('quality_holds')
    op.drop_index(op.f('ix_pm_sensor_readings_tenant_id'), table_name='pm_sensor_readings')
    op.drop_index(op.f('ix_pm_sensor_readings_asset_id'), table_name='pm_sensor_readings')
    op.drop_index('ix_pm_readings_asset_metric_ts', table_name='pm_sensor_readings')
    op.drop_table('pm_sensor_readings')
    op.drop_index(op.f('ix_pm_maintenance_history_tenant_id'), table_name='pm_maintenance_history')
    op.drop_index(op.f('ix_pm_maintenance_history_asset_id'), table_name='pm_maintenance_history')
    op.drop_table('pm_maintenance_history')
    op.drop_index(op.f('ix_output_logs_tenant_id'), table_name='output_logs')
    op.drop_index('ix_output_logs_line_timestamp', table_name='output_logs')
    op.drop_index(op.f('ix_output_logs_line_id'), table_name='output_logs')
    op.drop_table('output_logs')
    op.drop_index(op.f('ix_inventory_stock_movements_tenant_id'), table_name='inventory_stock_movements')
    op.drop_index('ix_inventory_stock_movements_item_ts', table_name='inventory_stock_movements')
    op.drop_index(op.f('ix_inventory_stock_movements_item_id'), table_name='inventory_stock_movements')
    op.drop_table('inventory_stock_movements')
    op.drop_index(op.f('ix_chat_messages_tenant_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sop_query_logs_tenant_id'), table_name='sop_query_logs')
    op.drop_table('sop_query_logs')
    op.drop_index(op.f('ix_sop_documents_tenant_id'), table_name='sop_documents')
    op.drop_table('sop_documents')
    op.drop_index(op.f('ix_shift_schedules_tenant_id'), table_name='shift_schedules')
    op.drop_table('shift_schedules')
    op.drop_index(op.f('ix_sent_alerts_tenant_id'), table_name='sent_alerts')
    op.drop_table('sent_alerts')
    op.drop_index(op.f('ix_quality_inspection_records_tenant_id'), table_name='quality_inspection_records')
    op.drop_index('ix_quality_insp_tenant_part_char_ts', table_name='quality_inspection_records')
    op.drop_index('ix_quality_insp_tenant_line_ts', table_name='quality_inspection_records')
    op.drop_table('quality_inspection_records')
    op.drop_index(op.f('ix_quality_characteristics_tenant_id'), table_name='quality_characteristics')
    op.drop_index('ix_quality_char_tenant_part_name', table_name='quality_characteristics')
    op.drop_table('quality_characteristics')
    op.drop_index(op.f('ix_pm_assets_tenant_id'), table_name='pm_assets')
    op.drop_table('pm_assets')
    op.drop_index(op.f('ix_onboarding_progress_tenant_id'), table_name='onboarding_progress')
    op.drop_table('onboarding_progress')
    op.drop_index(op.f('ix_module_freshness_tenant_id'), table_name='module_freshness')
    op.drop_table('module_freshness')
    op.drop_index(op.f('ix_lines_tenant_id'), table_name='lines')
    op.drop_table('lines')
    op.drop_index(op.f('ix_inventory_items_tenant_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_chat_conversations_user_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_tenant_id'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alert_settings_tenant_id'), table_name='alert_settings')
    op.drop_table('alert_settings')
    op.drop_table('tenants')
    # ### end Alembic commands ###
